---
title: Animatie toevoegen aan een GameObject
hero_image: images/banner.png
description: Animatie toevoegen aan een GameObject
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - title: Animatie toevoegen aan een GameObject
