title: Add animation to a GameObject
hero_image: images/banner.png
description: Add animation to a GameObject
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - 
    title: Add animation to a GameObject
