---
title: Ajouter une animation à un GameObject
hero_image: images/banner.png
description: Ajouter une animation à un GameObject
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - title: Ajouter une animation à un GameObject
